CREATE TABLE school.school_profile(
    calendar_year INTEGER,
    acara_sml_id INTEGER,
    location_age_id INTEGER,
    school_age_id INTEGER,
    school_name VARCHAR,
    suburb VARCHAR,
    state VARCHAR,
    postcode VARCHAR,
    school_sector VARCHAR,
    school_type VARCHAR,
    campus_type VARCHAR,
    reporting_type VARCHAR,
    school_url VARCHAR,
    governing_body VARCHAR,
    governing_body_url VARCHAR,
    year_range VARCHAR,
    geolocation VARCHAR,
    icsea_score INTEGER,
    icsea_percentile INTEGER,
    sea_bottom_pct DECIMAL(5, 2),
    sea_lower_mid_pct DECIMAL(5, 2),
    sea_upper_mid_pct DECIMAL(5, 2),
    sea_top_pct DECIMAL(5, 2),
    teaching_staff_cnt INTEGER,
    teaching_staff_fte DECIMAL(6, 1),
    non_teaching_staff_cnt INTEGER,
    non_teaching_staff_fte DECIMAL(6, 1),
    total_enrolments INTEGER,
    girls_enrolments INTEGER,
    boys_enrolments INTEGER,
    enrolments_fte DECIMAL(6, 1),
    indigenous_enrol_pct DECIMAL(5, 2),
    lbote_yes_pct DECIMAL(5, 2),
    lbote_no_pct DECIMAL(5, 2),
    lbote_not_stated_pct DECIMAL(5, 2),
    PRIMARY KEY(calendar_year, acara_sml_id)
);