CREATE TABLE school.school_location (
    calendar_year INTEGER NOT NULL,
    acara_sml_id INTEGER NOT NULL,
    location_age_id INTEGER,
    school_age_id INTEGER,
    rolled_school_id INTEGER,
    school_name VARCHAR,
    suburb VARCHAR,
    state VARCHAR,
    postcode VARCHAR,
    school_sector VARCHAR,
    school_type VARCHAR,
    special_school_flag INTEGER,
    campus_type VARCHAR,
    latitude DOUBLE,
    longitude DOUBLE,
    abs_ra_code INTEGER,
    abs_ra_name VARCHAR,
    meshblock_code VARCHAR,
    sa1_code VARCHAR,
    sa2_code VARCHAR,
    sa2_name VARCHAR,
    sa3_code VARCHAR,
    sa3_name VARCHAR,
    sa4_code VARCHAR,
    sa4_name VARCHAR,
    lga_code VARCHAR,
    lga_name VARCHAR,
    state_ed_code VARCHAR,
    state_ed_name VARCHAR,
    cth_ed_code VARCHAR,
    cth_ed_name VARCHAR,
    UNIQUE (calendar_year, acara_sml_id, location_age_id)
);
